### ISSUE TITLE
The algorithm: Diversity with one latent factor?

### ISSUE THREAD

**Issue by dirkphilip** [twitter/communitynotes#100]
Hello! 

Thanks for sharing this code with the community!
However, as I've been trying to understand the algorithm, I've become a bit confused. It seems like the Matrix Factorization model for Community Notes only uses a single latent variable, which means there's only one feature to model the diversity of notes and users. 

This must make it difficult to capture the full range of differences between people. With only one feature per person, how can you hope to capture things like race, gender, preferences, age, political views, cultural background, and so on? 

Intuitively, with just one variable, the only information you can use is whether a rater would typically agree or disagree with the average. The [Wikipedia article on Matrix Factorizations](https://en.wikipedia.org/wiki/Matrix_factorization_(recommender_systems)#cite_note-Jannach13-5) seems to confirm this, stating that a matrix factorization with one latent factor is equivalent to a top popular recommender (e.g., one that recommends the items with the most interactions without personalization). 

I understand that significant regularization is applied to the note intercept term, which means any notes with a high intercept term must have been accepted by both classes of people. However, I wonder how this approach compares to simply using average helpfulness scores along with the variance in ratings. 

This way, you could show notes that are both on average helpful and non-polarizing (low variance) (as long as enough people saw the note). I think this would produce similar results as the current algorithm, but it would be easier to understand and compute. What are your thoughts on this?  

Finally, I'm curious about how to assess the performance of the algorithm. How do we know that the notes are actually helpful for an actually diverse group of people? This is crucial information if want to try to improve the algorithm.

**Comment by jbaxter** [comment]
Thanks for the comment! Indeed, we designed the algorithm in such a way so that it is easy to increase the dimensionality later, once there is enough data (hopefully we can do this in not too long!), in order to represent more dimensions of viewpoint than just the major axis of disagreement.

> Intuitively, with just one variable, the only information you can use is whether a rater would typically agree or disagree with the average. The [Wikipedia article on Matrix Factorizations](https://en.wikipedia.org/wiki/Matrix_factorization_(recommender_systems)#cite_note-Jannach13-5) seems to confirm this, stating that a matrix factorization with one latent factor is equivalent to a top popular recommender (e.g., one that recommends the items with the most interactions without personalization).

This is true in a vanilla matrix factorization, but we have added in separate note and rater intercept terms that capture the overall popularity of a note, and whether a rater would typically agree or disagree. So then the factor is left to capture a separate dimension of disagreement than just raw popularity or rating leniency.

> However, I wonder how this approach compares to simply using average helpfulness scores along with the variance in ratings.

Feel free to prototype such an algorithm and compare the results! It'd be amazing to have algorithm contributions from others. Internally, we tried something like this and found the current production algorithm to work better.

> Finally, I'm curious about how to assess the performance of the algorithm. How do we know that the notes are actually helpful for an actually diverse group of people? This is crucial information if want to try to improve the algorithm.

Excellent question. We are working towards being able to release more and more of our evaluation criteria over time. In the meantime, we wrote up some of them in this paper (we used a survey as well as an A/B test): https://arxiv.org/pdf/2210.15723.pdf
