### ISSUE TITLE
A way to leave Community Notes

### ISSUE THREAD

**Issue by kenara** [twitter/communitynotes#123]
**Is your feature request related to a problem? Please describe.**
I signed up for Community Notes but I find that the content I am exposed to can be unpleasant and hurtful. Also, as a sometime Wikipedian, I thought it might be interesting or even fun. So far though, I've had no impact and engaging with flat-earth or other intentionally misleading nonsense is a waste of my time. I want out!

I haven't found a link, button etc to remove myself from the program.

**Describe the solution you'd like**
A way to quit the program, with an option to explain why.

**Describe alternatives you've considered**
The only alternative would be to stop using Twitter... 

[update: I'm using Twitter less]

And, I can't even DM @lucasnantonio as I'm not verified!

**Additional context**

**Comment by elvey** [comment]
You could open a new account.  But I hear you. 

Update: 
FAQ answers this: 
Q:How do I opt-out of the program?
A:If you join the program but later want to leave, DM @CommunityNotes to let the team know.

I doubt this works though - reading between the lines of  https://github.com/twitter/communitynotes/issues/84#issuecomment-1654754959
Please comment here if it does.

**Comment by maietta** [comment]
Have you tried reaching out directly with a DM to "communitynotes" X handle with this suggestion? You can also @ them publicly. I would use something like "Option to opt-out of contributing to Community Notes" or "No longer wish to participate in Community Notes"

**Comment by kenara** [comment]
Yep.. I sent them a DM two weeks ago! 

Since then I've seen in the [FAQ](https://communitynotes.twitter.com/guide/en/about/faq) that that's the recommended way out. So I guess it's an FAQ or expected to be one!

Also, because it's my organization's account, I hesitate to @ them publicly..

**Comment by kenara** [comment]
@elvey I manage an organization account with 160k followers but mostly stay within "professional Twitter". It's only when I get drawn into "cesspit Twitter" (like when I've been shifted into "For you") that I see the junk stuff. Content moderation should be done by paid staff with psychosocial support.

**Comment by maietta** [comment]
@kenara I understand. Thanks for the response on this.

**Comment by ghost** [comment]
They still aren't responding. 

"You can check in any time you like, but you can never leave"

**Comment by kenara** [comment]
@BlazingRaven495, nowadays, I mostly ignore invitations to review Community Notes. It's interesting to see from @jbaxter's Twitter account [https://twitter.com/_jaybaxter_](https://twitter.com/_jaybaxter_) that Notes are actually thriving because in my corner of the Twitterverse, Notes are 99.9% system abuse since the underlying Tweets are factual. 

I no longer care about leaving. Seeing that a Tweet has Notes gives me a sense of what we're up against and I'm not obliged to click through and read the offensive content. Seeing an invitation to review a Note is still relevant to my Twitter experience, certainly more so than seeing an ad!

**Comment by BlazingRaven495** [comment]
@jbaxter can honestly go fuck himself

**Comment by ghost** [comment]
damn, how is this not a thing?

**Comment by Pl8tinium** [comment]
i atleast found out how to opt out of the notifications

on the web interface 

-> go to community notes on the left

-> click your profile

-> click the gear icon in the top right corner

-> configure how frequently u want to be messaged (never)

**Comment by zchgdn** [comment]
Removing notifications doesn't solve the core issue here. There _should_ be a clear, simple way to just leave this program. I shouldn't have to make a new account to stop being inundated with community notes when 1/3rd of them are in bad faith, and another 1/3rd are clearly jokes or memes.

Since there's clearly no work being done to implement such a basic UX feature and since DMing 'CommunityNotes' on Twitter/X doesn't actually result in anything, anyone using Twitter in a web browser can use whatever browser plugin that allows custom CSS and add the following. It will hide the Community Notes link in the left-hand menu, as well as the community note/proposed community note from underneath a tweet (the third line targets some small text that occasionally appears when notes are only shown to select audiences):

`[aria-label*="Community Notes"],`
`[data-testid*="birdwatch"],`
`[data-testid*="birdwatch"] + div[style*="text-overflow"] {`
`    display: none !important;`
`}`

I imagine this will change at some point (given the data-testid attribute) but at the time of writing this, this has been my solution for a week or so.

**Comment by boomchigger** [comment]
I have reported this repository to Github Support for false information since Community Notes devs' FAQ solution of DMing community notes on Twitter and asking to be removed does not work. They are currently looking into it.

**Comment by maietta** [comment]
> I have reported this repository to Github Support for false information since Community Notes devs' FAQ solution of DMing community notes on Twitter and asking to be removed does not work. They are currently looking into it.

You have two great options:

You could send @ Support over on X instead of wasting people's time here.

Or, you could perform a pull request with your suggested corrections, which is exactly what Github was designed for.

**Comment by boomchigger** [comment]
> You have two great options:
> 
> You could send @ Support over on X instead of wasting people's time here.
> 
> Or, you could perform a pull request with your suggested corrections, which is exactly what Github was designed for.

X literally were lazy and closed my case and because it was "closed" they couldn't open it again. Also already tried contacting them a second time, no response. Also already tried to make a pull request about this on this and it was deleted within 6 hours.

**Comment by boomchigger** [comment]
> You have two great options:
> 
> You could send @ Support over on X instead of wasting people's time here.
> 
> Or, you could perform a pull request with your suggested corrections, which is exactly what Github was designed for.

update: I need to be a collaborator to make a pull request.

**Comment by elvey** [comment]
I sense you're frustrated, @boomchigger.  Nonetheless, you need to stop abusing github.  Like @twitterbirdwatch (i.e. @CommunityNotes on X) not looking at its DMs, commenting here as you did is bad netiquette.  Moreover, your spamming the same comment **_about reporting the whole repository_** to issue #84 in addition was way over the top.  I urge you to delete it. 
You're wasting the time of people like me who can do NOTHING to resolve your problem.  You need to be considerate - as does X.  That is required by the CoC.  Couldn't hurt if you mentioned your @username on X. What is your @username on X?
It looks like some of your activity has already been deleted because you're being disruptive? All that's visible is https://github.com/orgs/community/discussions/123565. 

Also, see https://github.com/twitter/communitynotes/issues/123#issuecomment-2078066898 [UPDATE: and/or  https://github.com/twitter/communitynotes/issues/123#issuecomment-2041504784 for workarounds.  **And there's a third workaround: you can delete your X account.  Your CN activity will thereby be deleted.** ]

Apropos @maietta's suggestion, it looks like @support on X blocks DMs AND hasn't replied to anyone since early last year:
https://x.com/search?f=live&q=(from%3Asupport)%20filter%3Areplies&src=typed_query

**Comment by getblasphemous** [comment]
🤖👽✨😶‍🌫️🫀🧠🫁🤳🌎🌍🌏🍑🧭🚀🌐🗺️🎸🎥📽️📱🔋📟💸⛑️📡🔬

**Comment by boomchigger** [comment]
> I sense you're frustrated, @boomchigger. Nonetheless, you need to stop abusing github. Like @twitterbirdwatch (i.e. @communitynotes on X) not looking at its DMs, commenting here as you did is bad netiquette. Moreover, your spamming the same comment **_about reporting the whole repository_** to issue #84 in addition was way over the top. I urge you to delete it. You're wasting the time of people like me who can do NOTHING to resolve your problem. You need to be considerate - as does X. That is required by the CoC. Couldn't hurt if you mentioned your @username on X. What is your @username on X? It looks like some of your activity has already been deleted because you're being disruptive? All that's visible is https://github.com/orgs/community/discussions/123565.
> 
> Also, see [#123 (comment)](https://github.com/twitter/communitynotes/issues/123#issuecomment-2078066898) for a workaround.
> 
> Apropos @maietta's suggestion, it looks like @support on X blocks DMs AND hasn't replied to anyone since early last year: https://x.com/search?f=live&q=(from%3Asupport)%20filter%3Areplies&src=typed_query

none of my activity has been deleted. Github support is still investigating this repository.

**Comment by jiansongc** [comment]
You can now opt out yourself without DMing @communitynotes, see the updated [FAQ](https://communitynotes.x.com/guide/en/about/faq):

**How do I opt-out of the program?**

If you join the program but later want to leave, you can do so in your [Community Notes settings](https://x.com/i/communitynotes/notification_settings).

If you leave and then later want to re-join, you can do so on your [Community Notes alias profile](http://x.com/i/communitynotes/u/me).

**Comment by zchgdn** [comment]
I don't know if this is actually fully fixed. I've left the program and while I'm not able to access Community Notes from the sidebar or menu (on both web browser (Chrome, FF, Edge tested)) and latest version of the app for iOS (I'm on an iPhone 13), when I do get a tweet with a community note, I'm able to vote on it or add notes. I can also confirm I've left the program:

![Screenshot_65](https://github.com/user-attachments/assets/3c803791-2db6-4da1-8aa5-025517ca4570)
![Screenshot_63](https://github.com/user-attachments/assets/c593c7c6-6aff-45f0-9247-39f065ad2c80)
![Screenshot_64](https://github.com/user-attachments/assets/f70168ad-f27c-4742-8a53-0526e1c17630)
![Screenshot_66](https://github.com/user-attachments/assets/ec8e10f6-24ab-4cf8-902b-0c1c3f1c898b)

**Comment by jiansongc** [comment]
Thanks for the feedback Zach.

Rating "Currently rated helpful" notes is available for X users that are not Community Notes contributors too. The difference is for non-contributors, their ratings won't be included for scoring notes - so these ratings will not affect whether a note will show or not show as a "Currently rated helpful" note.

**Comment by zchgdn** [comment]
Makes sense from that standpoint. I was more so speaking from a UX perspective; it is a little unclear and does seem like I still have some rudimentary access to contributing to Community Notes still (since if I click 'Somewhat' or 'No', I'm still able to add my own note) so just wanted to throw my $0.02 in!

**Comment by jiansongc** [comment]
> since if I click 'Somewhat' or 'No', I'm still able to add my own note

Do you mind uploading a screenshot for this case? This might not be expected.

**Comment by zchgdn** [comment]
You know what, that might've been weird browser caching nonsense on my end. Seems I can't add a note now as intended. Sorry!

**Comment by jiansongc** [comment]
No worries, thanks again for the feedback!

**Comment by ls253** [comment]
I am a member on Twitter X. One week ago they locked my account because I needed to update my information. I had changed my email address. I couldn't get back onto X. I lost all of my followers, this is not the first time that X has done this to me. The first time I lost 1260 followers. The second time I lost 620 followers. I currently have no followers, and according to Google I don't really have an X account. I have tried to get a hold of x through the help center, but there isn't a live person only a bot. Everything evolves around a bot. I tried their I phone number at San Francisco office, another bot! Be sure you have updated all of your information on x, or you as well will be going through this situation. Any advice from anyone would be helpful. Thank you! Linda Susan
