### ISSUE TITLE
Writing and rating community notes whose author is blocked by the tweet's author

### ISSUE THREAD

**Issue by xcsf6** [twitter/communitynotes#124]
* Is it possible to write and rate community notes whose author is blocked by the tweet's author ?
* If not, tweet's authors and note's evaluators are always in the same clusters of ideas like political ideologies and religions and personal preferences.

**Comment by jbaxter** [comment]
> Is it possible to write and rate community notes whose author is blocked by the tweet's author ?
In order to respect blocks on the platform, it is not currently possible unfortunately.

>If not, tweet's authors and note's evaluators are always in the same clusters of ideas like political ideologies and religions and personal preferences.
Luckily, blocks are currently rare enough that this statement is far from true in general. Agreed this is a limitation but we must respect the way blocks work on the platform. Do you have ideas for solutions, beyond the obvious - signup up for Community Notes with an alt account that you don't Tweet from in order to avoid getting blocked?
