### ISSUE TITLE
Passing in multiple rating TSV files to the scoring algorithm

### ISSUE THREAD

**Issue by rmovva** [twitter/communitynotes#150]
Hi, 

Now that there are sufficiently many ratings to split the rating data into two TSVs, how do we run main.py while passing in multiple rating filepaths as command line args? Or is the expected usage to combine the two files into one and then pass that in?

Thanks,
Raj

**Comment by jbaxter** [comment]
Thanks Raj! Apologies for the response delay here. The public code doesn't yet support reading multiple rating files at once. Rather than having to pass each individual filename I think a nicer solution may be to pass a directory and read all the files in the directory (or perhaps all the files that match the expected name format). We can fix this shortly! Or if you already have, feel free to put it up as a PR.

**Comment by avalanchesiqi** [comment]
I created a PR on this. I tested the function on the four TSV files available as of today. 

Usage: replacing the TSV file path by the directory path containing all TSV files

```
python main.py    --enrollment data/userEnrollment-00000.tsv \
    --notes data/notes-00000.tsv \
    --ratings data/ratings \
    --status data/noteStatusHistory-00000.tsv \
    --outdir data
```

**Comment by jbaxter** [comment]
Thank you @avalanchesiqi -- merged it!
