### ISSUE TITLE
Apply community notes algorithm to tweets and likes

### ISSUE THREAD

**Issue by fdietze** [twitter/communitynotes#260]
Hi, I was wondering if there is a good reason why the community notes algorithm is not applied to rank tweets in the user's feeds. It has great bridging properties which should help to work against polarization on the platform.

Instead of only applying it to notes and helpfulness, it could also be applied to tweets and likes. That should favor tweets which are liked by a diverse audience.

**Comment by jbaxter** [comment]
Thanks! Closing since not part of Community Notes, but we love this idea too.

One thing to keep in mind is that naively applying the Community Notes algorithm to like data results in generic content that is liked by everyone: think memes, funny videos, etc. So probably you want to only do bridging on the controversial issues.

**Comment by fdietze** [comment]
Thanks for your reply. That's a very good insight.

Where is a better place to talk about this?
